### ISSUE TITLE
怎能少了 babymetal ?

### ISSUE THREAD

**Issue by twhuang28** [GitYCC/yi-lee-birthday-card#2]
https://www.google.com/search?q=babymetal&tbm=isch&ved=2ahUKEwjZz-aqwL3uAhVREHAKHdtFDS8Q2-cCegQIABAA&oq=babymetal&gs_lcp=CgNpbWcQA1AAWABg3wpoAHAAeACAAQCIAQCSAQCYAQCqAQtnd3Mtd2l6LWltZw&sclient=img&ei=3BYSYNnxLNGgwAPbi7X4Ag&bih=462&biw=1024&rlz=1C1GCEU_zh-TWTW869TW869#imgrc=iAjiy-Yp8t1_NM

**Comment by YClabs** [comment]
As you wish!
